apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.2.0
      sourceRef:
        kind: HelmRepository
        name: postgresql
      interval: 5m
