apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ruby-app
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres
      namespace: dev
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./gitops/apps/overlays/dev/ruby-app/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 10m
  retryInterval: 1m
  timeout: 5m
