apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base/ruby-app
configMapGenerator:
  - name: ruby-app-values-overrides
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
