envs:
  RAILS_DEVELOPMENT_HOSTS: "dev-51-250-109-184.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  dev-51-250-109-184.nip.io:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev
    extraTls:
      - hosts:
          - "dev-51-250-109-184.nip.io"
        secretName: letsencrypt-dev-crt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: http
            path: "/"
