envs:
  RAILS_DEVELOPMENT_HOSTS: "stage-51-250-109-184.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  stage-51-250-109-184.nip.io:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-stage
    extraTls:
      - hosts:
          - "stage-51-250-109-184.nip.io"
        secretName: letsencrypt-stage-crt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: http
            path: "/"
