apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres-stage
spec:
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./gitops/apps/overlays/stage/postgres/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 10m
  retryInterval: 1m
  timeout: 5m
