envs:
  RAILS_DEVELOPMENT_HOSTS: "ruby-51-250-109-184.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  ruby-51-250-109-184.nip.io:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev-issuer-account-key
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
