envs:
  RAILS_DEVELOPMENT_HOSTS: "ruby-84-252-134-95.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  ruby-84-252-134-95.nip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt-dev
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
