envs:
  RAILS_DEVELOPMENT_HOSTS: "ruby-51-250-109-184.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  ruby-51-250-109-184.nip.io:
    tlsName: &sec ruby-app-tls-cert
    annotations:
      cert-manager.io/cluster-issuer: *sec
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
