envs:
  RAILS_DEVELOPMENT_HOSTS: "51.250.34.111.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  51.250.34.111.nip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
