envs:
  RAILS_DEVELOPMENT_HOSTS: "ruby-51-250-109-184.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  ruby-51-250-109-184.nip.io:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "128m"
      acme.cert-manager.io/http01-edit-in-place: "true"
    # certManager:
    # issuerType: cluster-issuer
    # issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
