envs:
  RAILS_DEVELOPMENT_HOSTS: "51.250.34.111.ip.io"

deployments:
  web-app:
    replicas: 2
    containers:
      - name: web-app
        envConfigmaps:
          - envs

ingresses:
  51.250.34.111.ip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
