ingresses:
  "*":
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
    - paths:
      - pathType: Prefix
        serviceName: web-app
        servicePort: 3000
