ingresses:
  any:
    ingressClassName: nginx
    hosts:
      - hostname: "*"
        paths:
          - path: "/"
            pathType: Prefix
            serviceName: web-app
            servicePort: 3000
