ingresses:
  130.193.44.115.nip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - hostname: 130.193.44.115.nip.io
        paths:
          path: "/"
          pathType: Prefix
          serviceName: web-app
          servicePort: 3000
