envs:
  RAILS_DEVELOPMENT_HOSTS: "ruby-130-193-46-237.nip.io"

deployments:
  web-app:
    replicas: 2

ingresses:
  ruby-130-193-46-237.nip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
