deployments:
  web-app:
    containers:
      - name: web-app
        imageTag: sha-94a95a2
        env:
          - name: RAILS_DEVELOPMENT_HOSTS
            value: "130.193.44.115.nip.io"

ingresses:
  130.193.44.115.nip.io:
    certManager:
      issuerType: cluster-issuer
      issuerName: letsencrypt
    ingressClassName: nginx
    hosts:
      - paths:
          - serviceName: web-app
            servicePort: 3000
            path: "/"
