apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.16.*
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 5m
