apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m
  timeout: 15m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.16.*
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 10m