apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-manager
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: *app
      version: 1.16.*
      sourceRef:
        kind: HelmRepository
        name: *app
      interval: 5m
