apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: ./gitops/infrastructure/cert-manager-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
