apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  path: ./gitops/infrastructure/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
