apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ruby-app
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: nxs-universal-chart
      version: 2.8.*
      sourceRef:
        kind: HelmRepository
        name: nxs-universal-chart
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: rails-app-values
    - kind: ConfigMap
      name: rails-app-values-overrides
