apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ruby-app
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: ruby-app-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
