envs:
  DB_HOST: postgres-postgresql
  DB_PORT: "5432"
  DB_USERNAME: postgres
  # DB_PASSWORD:
  #   valueFrom:
  #     secretKeyRef:
  #       name: postgres-postgresql
  #       key: postgres-password

defaultImage: mishila/mylab-ruby-app
defaultImageTag: latest
defaultImagePullPolicy: Always

deployments:
  web-app:
    replicas: 1
    labels:
      app: web-app
    podLabels:
      app: web-app
    containers:
      - name: web-app
        envConfigmaps:
          - envs
        envFrom:
          - secretKeyRef:
            name: postgres-postgresql
        ports:
          - containerPort: 3000

services:
  web-app:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 3000
