envs:
  DB_HOST: postgres-postgresql
  DB_PORT: "5432"
  DB_USERNAME: postgres

defaultImage: mishila/mylab-ruby-app
defaultImageTag: latest

deployments:
  web-app:
    replicas: 1
    labels:
      app: web-app
    podLabels:
      app: web-app
    containers:
      - name: web-app
        imagePullPolicy: Always
        env:
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgres-password
        envConfigmaps:
          - envs
        ports:
          - containerPort: 3000

services:
  web-app:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 3000
