deployments:
  web-app:
    replicas: 1
    labels:
      app: web-app
    podLabels:
      app: web-app
    containers:
      - name: web-app
        image: mishila/mylab-ruby-app
        imageTag: sha-9a4c7ec
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: postgres-postgresql
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-postgresql
                key: postgres-password
          - name: ALLOWED_HOST
            value: ".nip.io"
        ports:
          - containerPort: 3000

services:
  web-app:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 3000
