deployments:
  web-app:
    replicas: 1
    labels:
      app: web-app
    podLabels:
      app: web-app
    containers:
      - name: web-app
        image: mishila/mylab-ruby-app
        imageTag: latest
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            values: my-release-postgresql
          - name: DB_PORT
            values: 5432
          - name: DB_USERNAME
            values: postgres
          - name: DB_PASSWORD
            valuesFrom:
              secretKeyRef:
                name: my-release-postgresql
                password: postgres-password
        ports:
          - containerPort: 3000

services:
  web-app:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 3000
